apiVersion: v1
entries:
  hadoop:
  - apiVersion: v1
    appVersion: 3.3.9
    created: "2023-08-17T16:15:24.698221+01:00"
    description: The Apache Hadoop software library is a framework that allows for
      the distributed processing of large data sets across clusters of computers using
      simple programming models.
    digest: 5e655a09f2e502dfaf6350333698e6969c796ff4fefa15cc6e1b0b4f82f9e05e
    home: https://hadoop.apache.org/
    icon: http://hadoop.apache.org/images/hadoop-logo.jpg
    maintainers:
    - email: lancelot_zhu@163.com
      name: lancelotzhu
      url: http://github.com/lancelotzhu
    name: hadoop
    sources:
    - https://github.com/lancelotzhu/charts
    - https://github.com/apache/hadoop
    version: 1.0.0
generated: "2023-08-17T16:15:24.697105+01:00"
