apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-hive-ms
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    helm.sh/chart: {{ include "hadoop.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hive-ms
spec:
  serviceName: {{ include "hadoop.fullname" . }}-hive-ms
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: hive-ms
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: hive-ms
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: {{ include "hadoop.name" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
                app.kubernetes.io/component: hive-ms
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "hadoop.name" . }}
                  app.kubernetes.io/instance: {{ .Release.Name }}
                  app.kubernetes.io/component: hive-ms
        {{- end }}
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: wait-nn
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', "until curl -m 3 -sI http://{{ include "hadoop.fullname" . }}-hdfs-nn.{{ .Release.Namespace }}.svc.cluster.local:9870 | egrep --silent 'HTTP/1.1 200 OK|HTTP/1.1 302 Found'; do echo waiting for nn; sleep 1; done"]
      containers:
      - name: hive-ms
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
           - "/bin/bash"
           - "/tmp/hive-config/bootstrap.sh"
           - "-d"
        resources:
{{ toYaml .Values.hive.metaStore.resources | indent 10 }}
        # readinessProbe:
        #   tcpSocket:
        #     port: 10000
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 2
        # livenessProbe:
        #   tcpSocket:
        #     port: 10000
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 2
        volumeMounts:
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
        - name: hive-config
          mountPath: /tmp/hive-config
        - name: warehouse
          mountPath: /user/hive/warehouse
      volumes:
      - name: hadoop-config
        configMap:
          name: {{ include "hadoop.fullname" . }}
      - name: hive-config
        configMap:
          name: {{ include "hadoop.fullname" . }}-hive
      {{- if .Values.persistence.metaStore.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: warehouse
      labels:
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        helm.sh/chart: {{ include "hadoop.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: hdfs-ms
    spec:
      accessModes:
      - {{ .Values.persistence.metaStore.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.metaStore.size | quote }}
    {{- if .Values.persistence.metaStore.storageClass }}
    {{- if (eq "-" .Values.persistence.namemetaStoreNode.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.metaStore.storageClass }}"
    {{- end }}
    {{- end }}
      {{- else }}
      - name: warehouse
        emptyDir: {}
      {{- end }}