## @section Hadoop Parameters
##

image:
  repository: lancelotzhu/hadoop-ha
  tag: 3.3.6
  pullPolicy: Always

# The version of the hadoop libraries being used in the image.
hadoopVersion: 3.3.6
logLevel: INFO

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

hdfs:
  nameNode:
    replicas: 2
    pdbMinAvailable: 2
    
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  dataNode:
    replicas: 3
    pdbMinAvailable: 2

    # Will be used as dfs.datanode.hostname
    # You still need to set up services + ingress for every DN
    # Datanodes will expect to
    externalHostname: example.com
    externalDataPortRangeStart: 50500
    externalHTTPPortRangeStart: 51000

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  journalNode:
    # The number must be an odd one.
    replicas: 3
    pdbMinAvailable: 3

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"  

  webhdfs:
    enabled: true

yarn:
  resourceManager:
    replicas: 3
    pdbMinAvailable: 2

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"  

  nodeManager:
    replicas: 3
    pdbMinAvailable: 2

    # Create statefulsets in parallel (K8S 1.7+)
    parallelCreate: false

    resources:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

persistence:
  nameNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

  dataNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 200Gi

  journalNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

  # turn on/off zookeeper's persistence
  enabled: false


## @section External Zookeeper paramaters
##
externalZookeeper:
  ## @param externalZookeeper.servers List of external zookeeper servers to use
  ## @param externalZookeeper.port Port of the Zookeeper servers
  ##
  servers: []
  port: 2181

## @section Zookeeper subchart parameters
##
## @param zookeeper.enabled Deploy Zookeeper subchart
## @param zookeeper.replicaCount Number of Zookeeper instances
## @param zookeeper.service.ports.client Zookeeper client port
##
zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: false
  service:
    ports:
      client: 2181
  auth:
    enabled: false
  allowAnonymousLogin: true
